version: '3.8'

services:
  backend:
    container_name: backend
    image: ${HOST_FOR_DOCKER_IMAGE}/neptunessushi_backend_${ENVIRONMENT}:${VERSION}
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend_network
    depends_on:
      - sushi-db
    environment:
      - POSTGRES_HOST="sushi-db"
      - POSTGRES_PORT="5432"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    container_name: frontend
    image: ${HOST_FOR_DOCKER_IMAGE}/neptunessushi_frontend_${ENVIRONMENT}:${VERSION}
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_MAIN_API=${VITE_APP_MAIN_API}

  sushi-db:
    container_name: sushi-db
    image: postgres:14
    restart: always
    ports:
      - "5499:5432"
    networks:
      - backend_network
    volumes:
      - ${PROJECT_DATA_PATH}/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    networks:
      - backend_network
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_USERNAME=${DOZZLE_USERNAME}
      - DOZZLE_PASSWORD=${DOZZLE_PASSWORD}
      - DOZZLE_KEY=true

networks:
  backend_network:
    driver: bridge
